### ISSUE TITLE
Add a linter step to CI/CD

### ISSUE THREAD

**Issue by joshlory** [Fantaskink/SOTC#11]
To avoid nits in code reviews and fixups like 184b16f3a6e0338603c4dcf8cff8ef3e4344518e it may be worth adding a `lint` step to CI and a `./format.sh` script as a pre-commit hook.

https://github.com/Fantaskink/SOTC/blob/184b16f3a6e0338603c4dcf8cff8ef3e4344518e/.github/workflows/build.yml#L15-L26

**Comment by Fantaskink** [comment]
I've added a step that replaces int, short, long, etc with their fixed-width equivalents. Also added a clang-format step and a style file. The new workflow file will analyze all C source files, but will not format them at the moment.

**Comment by Fantaskink** [comment]
Removed the clang-format module and started installing it manually in the action. It will now automatically format any C files in ``src``. The style is based on VSCode's default format style and is defined in ``.clang-format``.
